# Generated by Django 5.1.1 on 2024-09-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0003_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
    ]
