# Generated by Django 5.1.1 on 2024-10-04 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('en attente', 'attente'), ('payée', 'payée'), ('expédiée', 'expédiée'), ('livrée', 'livrée')], max_length=100)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='siteweb.order')),
            ],
        ),
    ]
