# Generated by Django 5.1.1 on 2024-10-04 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0007_alter_command_order_alter_command_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteweb.command')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteweb.products')),
            ],
        ),
    ]
